bom_squad/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('users/', include('user_profile.urls')),
    path('modules/', include('modules.urls')),
    path('components/', include('components.urls')),
    path('', include('home.urls')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from home import views
from .views import search_results
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.index, name='home'),
    path('search/', views.search_results, name='search_results'),
    path('add_to_built/<int:id>', views.add_to_built, name='AddToBuilt'),
    path('remove_from_built/<int:id>', views.remove_from_built, name='RemoveFromBuilt'),
    path('add_to_to_build/<int:id>', views.add_to_to_build, name='AddToToBuild'),
    path('remove_from_to_build/<int:id>', views.remove_from_to_build, name='RemoveFromToBuild')
]

modules/urls.py
from django.urls import path
from modules import views
from django.views.generic import RedirectView

app_name = 'modules'

urlpatterns = [
    path('', RedirectView.as_view(url='/')),
    path('<slug:slug>/<int:id>', views.add_to_shopping_list, name='AddToShoppingList'),
    path('<slug:slug>/data/', views.data, name='ModuleData'),
    path('<slug:slug>/', views.module_detail, name='ModuleDetail'),
]

user_profile/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('me/', views.me, name='me'),
    path('add_components_to_shopping/', views.addComponentsToShoppingList, name="add-shopping"),
    path('add_components_to_inventory/', views.addComponentsToComponentInventoryList, name="add-inventory"),
    path('inventory_data/csv/', views.export_inventory_data_csv, name='export_inventory_data_csv'),
    path('update_inventory/', views.update_inventory, name='update_inventory'),
    path('update_inventory_quantity/<int:pk>', views.update_inventory_quantity, name='update_inventory_quantity'),
    path('update_inventory_location/<int:pk>', views.update_inventory_location, name='update_inventory_location'),
    path('delete_inventory_item/<int:pk>', views.delete_inventory_item, name='delete_inventory_item'),
    path('user_inventory/', views.user_inventory, name='user_inventory'),
    path('<slug:slug>/', views.user_page, name='user_page'),
]

user_profile/models.py
from django.db import models
from django.utils import timezone
from django.template.defaultfilters import slugify
from modules.models import Module, Component, ModuleBomListItem
from django.contrib.auth.models import User
import ast

def StringToJSON(input_to_test):
    try:
        return ast.literal_eval(input_to_test)
    except:
        return ast.literal_eval("{}")

class UserProfile(models.Model):
    user = models.OneToOneField(User, unique=True, on_delete=models.CASCADE)
    built_modules = models.ManyToManyField(Module, blank=True, related_name='built')
    want_to_build_modules = models.ManyToManyField(Module, blank=True, related_name='want_to_build')
    component_inventory = models.ManyToManyField(Component, blank=True, related_name='user_component_inventory',
                                                 through='UserProfileComponentInventoryData')
    shopping_list = models.ManyToManyField(Component, blank=True, related_name='user_shopping_list',
                                                 through='UserProfileShoppingListData')
    component_inventory_json = models.JSONField(null=True, blank=True)
    shopping_list_json = models.JSONField(null=True, blank=True)
    slug = models.SlugField(blank=True)

    def save(self, *args, **kwargs):
        if type(self.component_inventory_json) is str:
            self.component_inventory_json = StringToJSON(self.component_inventory_json)
        if type(self.shopping_list_json) is str:
            self.shopping_list_json = StringToJSON(self.shopping_list_json)
        if not self.slug:
            self.slug = slugify(f"{self.user}")
            super(UserProfile, self).save(*args, **kwargs)
        else:
            super(UserProfile, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.user}"

    class Meta:
        verbose_name_plural = "User Extended Properties"

class UserProfileComponentInventoryData(models.Model):
    component = models.ForeignKey(Component, null=True, on_delete=models.SET_NULL)
    profile = models.ForeignKey(UserProfile, null=True, on_delete=models.SET_NULL)
    quantity = models.PositiveIntegerField(default=0, blank=False)
    location = models.JSONField(null=True, blank=True)

    class Meta:
        # unique_together = ('component', 'profile', 'location')
        verbose_name_plural = "User Component Inventory"

    def __str__(self):
        return f'[ {self.profile} ] - [ {self.location} ] - {self.component}'

# Allows users to add modules to a named list
# All modules are also in a default "all" list which is just
class UserShoppingLists(models.Model):
    name = models.CharField(max_length=255, blank=False)
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "User-Defined, Named Shopping Lists"

    def __str__(self):
        return f'[ {self.user} ] - {self.name}'

class UserProfileShoppingListData(models.Model):
    module = models.ForeignKey(Module, on_delete=models.CASCADE)
    bom_item = models.ForeignKey(ModuleBomListItem, on_delete=models.CASCADE)
    component = models.ForeignKey(Component, on_delete=models.CASCADE)
    profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    number = models.PositiveIntegerField(default=0, blank=False)
    tags = models.JSONField(blank=True, null=True)

    class Meta:
        verbose_name_plural = "User Shopping List"

    def __str__(self):
        return f'[ {self.profile} ] - {self.component}'

users/models.py
from django.db import models
from django.utils import timezone
from django.template.defaultfilters import slugify
from modules.models import Module
from django.contrib.auth.models import User


class UserExtended(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    built_modules = models.ForeignKey(Module, null=True, blank=True, on_delete=models.SET_NULL, related_name='built_modules')
    want_to_build_modules = models.ForeignKey(Module, null=True, blank=True, on_delete=models.SET_NULL, related_name='want_to_build_modules')
    component_inventory = models.JSONField(blank=True, null=True)
    slug = models.SlugField(blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(f"{self.first_name}_{self.last_name}")
            super(UserExtended, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.first_name}_{self.last_name}"

user_profile/views.py
from django.shortcuts import render, redirect
from rest_framework import status
from user_profile.models import UserProfile, UserProfileShoppingListData, Module, UserProfileComponentInventoryData
from components.models import Component
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django_gravatar.helpers import get_gravatar_url, has_gravatar, get_gravatar_profile_url, calculate_gravatar_hash
from django.http import HttpResponse
from user_profile.models import UserProfile
from django.core import serializers
from django.http import HttpResponse, JsonResponse
from rest_framework.decorators import api_view
import collections
from django import template
from django.db.models import JSONField
from user_profile.serializers import InventorySerializer
from django.shortcuts import get_object_or_404
from rest_framework.response import Response
import json

identical_lists = lambda x, y: collections.Counter(x) == collections.Counter(y)

def merge_shopping_lists(new_dict, old_dict):
    for key, value in new_dict.items():
        old_dict[key] = old_dict.get(key, {"quantity": 0})
        old_dict[key]["quantity"] += value["quantity"]

# Create your views here.
@login_required()
def user_page(request, **kwargs):

    built = None
    to_build = None

    current_user = UserProfile.objects.get(user=request.user)
    built = current_user.built_modules.all()
    to_build = current_user.want_to_build_modules.all()
    shopping_list_modules = UserProfileShoppingListData.objects.values("module").distinct()
    all_components_for_shopping_list = UserProfileShoppingListData.objects.values("component").distinct()

    user_email = request.user.email
    username = request.user.username

    gravatar_exists = has_gravatar(user_email)

    inventory = UserProfileComponentInventoryData.objects.all()
    location_strings = [json.dumps(item.location).replace('"', '').replace('[', '').replace(']', '') for item in inventory]
    zipped_data = zip(location_strings, inventory)
    context = {
        'current_user': current_user,
        'zipped_data': zipped_data,
        'built': built,
        'to_build': to_build,
        'shopping_list_modules': shopping_list_modules,
        'user_email': user_email,
        'gravatar_exists': gravatar_exists,
        'username': username,
    }

    return render(request, 'users/index.html', context)


@login_required()
@api_view(['GET'])
def user_inventory(request, **kwargs):
    user = UserProfile.objects.filter(user=request.user).first()
    inventory = UserProfileComponentInventoryData.objects.filter(profile=user)
    serializer = InventorySerializer(inventory, many=True)
    return Response(serializer.data)

@login_required()
def addComponentsToShoppingList(request):
    if request.method == 'POST':
        body_unicode = request.body.decode('utf-8')
        new_data = json.loads(body_unicode)

        # If empty data is submitted, return 203
        if not new_data.keys():
            return HttpResponse(status=204)

        # Make sure user is logged in
        if UserProfile.objects.get(user=request.user):

            # Get user's profile data
            user_data = UserProfile.objects.get(user=request.user)

            # If "user_data.shopping_list_json" is empty
            if not isinstance(user_data.shopping_list_json, dict):
                user_data.shopping_list_json = new_data
                user_data.save()
                return HttpResponse(status=200)

            # Iterate over module ids (as well as the anonymous category) and merge sub dicts by adding quantities
            for key, value in new_data.items():
                user_data.shopping_list_json[key] = merge_shopping_lists(new_data[key], user_data.shopping_list_json[key])

            user_data.save()
            return HttpResponse(status=200)

        else:
            # If user profile isn't found
            return redirect('login')
    else:
        # If not a POST request
        return HttpResponse(status=405)

@login_required()
def addComponentsToComponentInventoryList(request):
    if request.method == 'POST':
        body = json.loads(request.body)

        # If empty data is submitted, return 204
        if not body:
            return HttpResponse(status=204)

        # Get user's profile data
        user_profile = UserProfile.objects.get(user=request.user)

        for component_id, data in body.items():
            location = data.get("location", None)
            quantity = data["quantity"]

            try:
                inventory_item = UserProfileComponentInventoryData.objects.filter(component=component_id, profile=user_profile).all()
                if inventory_item:
                    for item in inventory_item:
                        if item.location == location:
                            item.quantity += int(quantity)
                            item.save()
                        else:
                            new_inventory_item = UserProfileComponentInventoryData.objects.create(
                                component_id=int(component_id), profile=user_profile,
                                quantity=quantity, location=location)
                            new_inventory_item.save()
                else:
                    new_inventory_item = UserProfileComponentInventoryData.objects.create(
                        component_id=int(component_id), profile=user_profile,
                        quantity=quantity, location=location)
                    new_inventory_item.save()

            except UserProfileComponentInventoryData.DoesNotExist:
                UserProfileComponentInventoryData.objects.create(component_id=component_id, profile=user_profile, quantity=quantity, location=location)

        return HttpResponse(status=200)

    else:
        # If not a POST request
        return HttpResponse(status=405)


import csv
from django.http import HttpResponse

def export_inventory_data_csv(request):
    inventory_data = UserProfileComponentInventoryData.objects.prefetch_related('component').values(
        'component__description',
        'quantity',
        'location'
    )
    new_data = []
    for data in inventory_data:
        if data['location']:
            for location in data['location']:
                new_data.append({
                    'component__description': data['component__description'],
                    'quantity': data['quantity'],
                    'location': location
                })
        else:
            new_data.append({
                'component__description': data['component__description'],
                'quantity': data['quantity'],
                'location': None
            })
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="inventory_data.csv"'

    writer = csv.DictWriter(response, fieldnames=['component__description','quantity','location'])
    writer.writeheader()
    for item in new_data:
        writer.writerow(item)

    return response
@login_required()
def update_inventory(request):
    if request.method == 'PUT':

        # Get data from the PUT request body
        data = json.loads(request.body)

        # Get the id of the inventory item to update
        id = data['id']

        # Get the new value for the field that needs to be updated
        new_value = data['value']

        # Get the field that needs to be updated
        field = data.get('field')

        try:
            # Get the user profile of the logged-in user
            user_profile = UserProfile.objects.get(user=request.user)

            # Get the inventory item that needs to be updated
            user_profile_component_inventory_data = UserProfileComponentInventoryData.objects.get(id=id, profile=user_profile)

            # Check if the logged in user is authorized to update this inventory
            if request.user.id != user_profile_component_inventory_data.profile.user.id:
                return JsonResponse({'error': 'You are not authorized to update this inventory'}, status=401)

            # Update the quantity field if the field is 'quantity'
            if field == 'quantity':
                user_profile_component_inventory_data.quantity = new_value

            # Update the location field if the field is 'location'
            elif field == 'location':
                user_profile_component_inventory_data.location = new_value

            # Save the updated inventory item
            user_profile_component_inventory_data.save()
            return JsonResponse({'success': 'Inventory updated successfully'}, status=200)
        except UserProfileComponentInventoryData.DoesNotExist:
            return JsonResponse({'error': 'Inventory not found'}, status=404)
        except UserProfileComponentInventoryData.DoesNotExist:
            return JsonResponse({'status': 'error'})

@login_required
def update_inventory_quantity(request, pk):
    inventory = get_object_or_404(UserProfileComponentInventoryData, pk=pk)
    if request.method == 'PATCH':
        if inventory.profile.user != request.user:
            return JsonResponse({'error': 'You do not have permission to update this inventory'}, status=403)
        data = json.loads(request.body)
        inventory.quantity = data['quantity']
        inventory.save()
        return JsonResponse({'message': 'Inventory quantity updated successfully'}, status=200)
    else:
        return JsonResponse({'error': 'Invalid request method'}, status=405)


@login_required
def update_inventory_location(request, pk):
    inventory = get_object_or_404(UserProfileComponentInventoryData, pk=pk)
    if request.method == 'PATCH':
        if inventory.profile.user != request.user:
            return JsonResponse({'error': 'You do not have permission to update this inventory'}, status=403)
        data = json.loads(request.body)
        inventory.location = data['location']
        inventory.save()

users/views.py
from django.shortcuts import render, redirect
from .models import UserExtended
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404

# Create your views here.
@login_required()
def user_page(request, slug):
    user_slug = UserExtended.objects.filter(user=slug)
    context = get_object_or_404(UserExtended, slug=user_slug[0].slug)
    return render(request, 'users/index.html', {"context": context})

user_profile/templates/users/profile_tabs/built-modules.html
<div class="row w-100">
    {% for module in current_user.built_modules.all %}
        <div class="card col-xs-12 col-sm-12 col-md-4 col-lg-3  py-4 m-2 d-flex justify-content-around"
             style="min-width: 270px; max-height: 548px">
            {% if module.image %}
                <img src="{% url 'home' %}{{ MEDIA_URL }}{{ module.image }}"
                     style="height: 200px; width: 100%; object-fit: contain" alt="{{ module.name }} panel"/>
            {% endif %}
            <div class="d-flex flex-column justify-content-around">
                <div class="card-body py-4 px-0" style="height: 261px">
                    <div class="d-flex justify-content-between w-100">
                        <div>
                            {% if not module.version or module.version == '0' or module.version == '1' %}
                                <h2 class="card-title h4"><a class="user-profile__card-title-link"
                                                             href="{% url 'modules:ModuleDetail' module.slug %}">{{ module.name }}</a>
                                </h2>
                            {% else %}
                                <h2 class="card-title h4"><a class="user-profile__card-title-link"
                                                             href="{% url 'modules:ModuleDetail' module.slug %}">{{ module.name }}
                                    (v{{ module.version }})</a></h2>
                            {% endif %}
                        </div>
                    </div>
                    <p class="card-title mb-3"><b><a class="user-profile__manufacturer-link">{{ module.manufacturer }}</a></b></p>
                    <div class="description-wrapped">
                        <p>{{ module.description }}</p>
                    </div>
                </div>
                <div class="text-nowrap d-flex justify-content-between" style="width: 100px;">
                    {% if built and module in built %}
                        {% include "home/buttons/built_svg_button.html" with add=False module_id=module.id request_path=request.path %}
                    {% else %}
                        {% include "home/buttons/built_svg_button.html" with add=True module_id=module.id request_path=request.path %}
                    {% endif %}
                    {% if to_build and module in to_build %}
                        {% include "home/buttons/to_build_svg_button.html" with add=False module_id=module.id request_path=request.path %}
                    {% else %}
                        {% include "home/buttons/to_build_svg_button.html" with add=True module_id=module.id request_path=request.path %}
                    {% endif %}
                </div>
            </div>
        </div>
    {% endfor %}
</div>

user_profile/templates/users/profile_tabs/shopping-list.html
<div class="row flex-nowrap my-4">
    {% for module in shopping_list_modules %}
        <div class="col-3 p-0">
            <div class="card card-block border-0 border-right" style="min-height: 30vh">
                <h1>{{ module }}</h1>
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Description</th>
                            <th scope="col">Item #</th>
                            <th scope="col">quantity</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Mark</td>
                            <td>Otto</td>
                            <td>@mdo</td>
                        </tr>
                        <tr>
                            <td>Jacob</td>
                            <td>Thornton</td>
                            <td>@fat</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    {% endfor %}
</div>

user_profile/templates/users/profile_tabs/want-to-build.html
<div class="card col-xs-12 col-sm-12 col-md-4 col-lg-3  py-4 m-2 d-flex justify-content-around"
     style="min-width: 270px; max-height: 548px">
    {% if module.image %}
        <img src="{% url 'home' %}{{ MEDIA_URL }}{{ module.image }}"
             style="height: 200px; width: 100%; object-fit: contain" alt="{{ module.name }} panel"/>
    {% endif %}
    <div class="d-flex flex-column justify-content-around">
        <div class="card-body py-4 px-0" style="height: 261px">
            <div class="d-flex justify-content-between w-100">
                <div>
                    {% if not module.version or module.version == '0' or module.version == '1' %}
                        <h2 class="card-title h4"><a class="user-profile__card-title-link"
                                                     href="{% url 'modules:ModuleDetail' module.slug %}">{{ module.name }}</a>
                        </h2>
                    {% else %}
                        <h2 class="card-title h4"><a class="user-profile__card-title-link"
                                                     href="{% url 'modules:ModuleDetail' module.slug %}">{{ module.name }}
                            (v{{ module.version }})</a></h2>
                    {% endif %}
                </div>
            </div>
            <p class="card-title mb-3"><b><a class="user-profile__manufacturer-link">{{ module.manufacturer }}</a></b></p>
            <div class="description-wrapped">
                <p>{{ module.description }}</p>
            </div>
        </div>
        <div class="text-nowrap d-flex justify-content-between" style="width: 100px;">
            {% if built and module in built %}
                {% include "home/buttons/built_svg_button.html" with add=False module_id=module.id request_path=request.path %}
            {% else %}
                {% include "home/buttons/built_svg_button.html" with add=True module_id=module.id request_path=request.path %}
            {% endif %}
            {% if to_build and module in to_build %}
                {% include "home/buttons/to_build_svg_button.html" with add=False module_id=module.id request_path=request.path %}
            {% else %}
                {% include "home/buttons/to_build_svg_button.html" with add=True module_id=module.id request_path=request.path %}
            {% endif %}
        </div>
    </div>
</div>